micronaut:
  application:
    name: mn
  server:
    port: 8081

---
datasources:
  default:
    url: jdbc:postgresql://localhost:26257/userinput
    driverClassName: org.postgresql.Driver
    username: root
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update